apiVersion: v2
name: traceroot
description: Observability and self-improving layer for AI agents
type: application
version: 1.0.1
appVersion: "0.1.0"

home: https://traceroot.ai
sources:
  - https://github.com/traceroot-ai/traceroot-k8s
  - https://github.com/traceroot-ai/traceroot
maintainers:
  - name: TraceRoot.AI
    url: https://github.com/traceroot-ai

dependencies:
  - name: clickhouse
    version: 8.0.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: clickhouse.deploy
