apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "traceroot.fullname" . }}-migrate-postgres
  labels:
    {{- include "traceroot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "traceroot.selectorLabels" . | nindent 8 }}
        app: migrate-postgres
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.migrations.postgres.image.repository }}:{{ .Values.migrations.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: {{ .Values.postgresql.secretKeys.databaseUrl }}
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
